apiVersion: apps/v1
kind: Deployment
metadata:
        name: nice-pod
        labels:
                pod: nice-pod
spec:
        selector:
                matchLabels:
                        pod: nice-pod
        replicas: 3
        template:
                metadata:
                        labels:
                                pod: nice-pod
                spec:
                        containers:
                        -       image: katacoda/docker-http-server:latest
                                imagePullPolicy: Always
                                name: nice-pod-container
