apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-monkey-sa
---
# The role granting pod kill in the default namespace.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: kube-monkey-role
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["delete", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kube-monkey-role-binding
  #  namespace: user-1-namespace
roleRef:
  apiGroup: ""
#  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kube-monkey-role
subjects:
- apiGroup: ""
#- apiGroup: rbac.authorization.k8s.io
  kind: ServiceAccount
  name: kube-monkey-sa



  #kubectl create rolebinding my-sa-view \
  # --clusterrole=view \
  #  --serviceaccount=my-namespace:my-sa \
  #  --namespace=my-namespace

