apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-monkey-sa
---
# The role granting pod kill in the default namespace.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: kube-monkey-role
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["delete", "list"]
---
# The role granting pod kill in the default namespace.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
        #namespace: default
  name: kube-monkey-depl-role
rules:
- apiGroups: ["apps"] # "apps" indicates the apps API group
  resources: ["deployments", "statefulsets", "daemonsets"]
  verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kube-monkey-pod-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kube-monkey-role
subjects:
- apiGroup: "" #rbac.authorization.k8s.io
  kind: ServiceAccount
  name: kube-monkey-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-monkey-deployment-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-monkey-depl-role
subjects:
- apiGroup: "" #rbac.authorization.k8s.io
  kind: ServiceAccount
  name: kube-monkey-sa
  namespace: default

