apiVersion: extensions/v1beta
kind: Deployment
metadata:
  name: nice-pod
spec:
  replicas: 1
  template:
    spec:
      containers:
      - image: katacoda/docker-http-server:latest
        imagePullPolicy: Always
        name: nice-pod-container
